import { Product } from "./types";

export const products: Product[] = [
  {
    id: "maybelline-fit-me-220",
    slug: "maybelline-fit-me-matte-poreless-220",
    name: "Fit Me Matte + Poreless Foundation 220",
    brand: "Maybelline",
    category: "makeup",
    priceKes: 1850,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/61vtQnuuF0L._SL1500_.jpg",
    description:
      "Oil-control liquid foundation for normal to oily Kenyan skin tones.",
    rating: 4.7,
    reviewsCount: 126,
  },
  {
    id: "maybelline-superstay-355",
    slug: "maybelline-superstay-full-coverage-355",
    name: "SuperStay Full Coverage Foundation 355",
    brand: "Maybelline",
    category: "makeup",
    priceKes: 2450,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/61v7lidh%2BnL._SL1500_.jpg",
    description:
      "Long‑wear, high‑coverage foundation that holds in Nairobi heat.",
    rating: 4.6,
    reviewsCount: 89,
  },
  {
    id: "la-girl-pro-conceal-fawn",
    slug: "la-girl-pro-conceal-fawn",
    name: "Pro Conceal HD Concealer Fawn",
    brand: "L.A Girl",
    category: "makeup",
    priceKes: 750,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/61d5v5lqHfL._SL1500_.jpg",
    description:
      "Creamy concealer for highlighting and correcting under Kenyan sun.",
    rating: 4.8,
    reviewsCount: 214,
  },
  {
    id: "la-girl-pro-matte-foundation",
    slug: "la-girl-pro-matte-liquid-foundation",
    name: "Pro Matte Liquid Foundation",
    brand: "L.A Girl",
    category: "makeup",
    priceKes: 1650,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/61L2dC9yGdL._SL1500_.jpg",
    description: "Soft matte, long‑wear foundation ideal for humid climates.",
    rating: 4.5,
    reviewsCount: 97,
  },
  {
    id: "black-opal-stick-truly-topaz",
    slug: "black-opal-true-color-stick-foundation-truly-topaz",
    name: "True Color Stick Foundation Truly Topaz",
    brand: "Black Opal",
    category: "makeup",
    priceKes: 2200,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/61Wss9Q0QML._SL1500_.jpg",
    description:
      "Iconic stick foundation formulated for deeper African skin tones.",
    rating: 4.9,
    reviewsCount: 64,
  },
  {
    id: "mac-studio-fix-fluid-nc45",
    slug: "mac-studio-fix-fluid-spf15-nc45",
    name: "Studio Fix Fluid SPF 15 NC45",
    brand: "MAC",
    category: "makeup",
    priceKes: 5200,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/51i8dBW1WzL._SL1100_.jpg",
    description:
      "Medium‑to‑full coverage foundation with SPF for city commutes.",
    rating: 4.7,
    reviewsCount: 73,
  },
  {
    id: "revlon-colorstay-combination-oily",
    slug: "revlon-colorstay-foundation-combination-oily",
    name: "ColorStay Foundation Combination/Oily",
    brand: "Revlon",
    category: "makeup",
    priceKes: 2100,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71g1NhRk5yL._SL1500_.jpg",
    description:
      "Shine‑control foundation that stays put through Nairobi traffic.",
    rating: 4.4,
    reviewsCount: 51,
  },
  {
    id: "milani-baked-blush-luminoso",
    slug: "milani-baked-blush-luminoso",
    name: "Baked Blush Luminoso",
    brand: "Milani",
    category: "makeup",
    priceKes: 1550,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71O3VddOZ2L._SL1500_.jpg",
    description: "Glowing peach blush that flatters Kenyan undertones.",
    rating: 4.8,
    reviewsCount: 132,
  },
  {
    id: "maybelline-lash-sensational",
    slug: "maybelline-lash-sensational-mascara",
    name: "Lash Sensational Mascara",
    brand: "Maybelline",
    category: "makeup",
    priceKes: 1350,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/81H6qM4Za6L._SL1500_.jpg",
    description: "Volumising mascara that resists smudging in warm weather.",
    rating: 4.7,
    reviewsCount: 201,
  },
  {
    id: "black-opal-true-color-powder",
    slug: "black-opal-true-color-powder",
    name: "True Color Soft Velvet Finishing Powder",
    brand: "Black Opal",
    category: "makeup",
    priceKes: 1850,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/61Tt1Ik5d5L._SL1200_.jpg",
    description: "Velvety setting powder for deeper complexions.",
    rating: 4.6,
    reviewsCount: 58,
  },
  {
    id: "la-girl-glide-liner-brown",
    slug: "la-girl-glide-gel-liner-brown",
    name: "Glide Gel Eyeliner Pencil Brown",
    brand: "L.A Girl",
    category: "makeup",
    priceKes: 650,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/61z4zJz%2B6aL._SL1500_.jpg",
    description: "Smooth gel eyeliner ideal for everyday Kenyan glam.",
    rating: 4.4,
    reviewsCount: 44,
  },
  {
    id: "revlon-super-lustrous-lipstick-rum-raisn",
    slug: "revlon-super-lustrous-lipstick-rum-raisin",
    name: "Super Lustrous Lipstick Rum Raisin",
    brand: "Revlon",
    category: "makeup",
    priceKes: 1150,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/51HB3wZ0qGL._SL1000_.jpg",
    description: "Classic creamy lipstick perfect for office to evening.",
    rating: 4.5,
    reviewsCount: 39,
  },
  {
    id: "mac-fix-plus-setting-spray",
    slug: "mac-prep-prime-fix-plus",
    name: "Prep + Prime Fix+ Setting Spray",
    brand: "MAC",
    category: "makeup",
    priceKes: 3800,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/51nQeXqQFhL._SL1000_.jpg",
    description: "Hydrating setting mist to refresh makeup throughout the day.",
    rating: 4.7,
    reviewsCount: 61,
  },
  {
    id: "maybelline-master-chrome-highlighter",
    slug: "maybelline-master-chrome-highlighter-molten-gold",
    name: "Master Chrome Highlighter Molten Gold",
    brand: "Maybelline",
    category: "makeup",
    priceKes: 1650,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/81m2VqCk2wL._SL1500_.jpg",
    description: "Golden highlighter that melts beautifully into deeper skin.",
    rating: 4.8,
    reviewsCount: 142,
  },
  {
    id: "milani-setting-spray-make-it-last",
    slug: "milani-make-it-last-setting-spray",
    name: "Make It Last Setting Spray",
    brand: "Milani",
    category: "makeup",
    priceKes: 1650,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71I4nDzvPZL._SL1500_.jpg",
    description:
      "Long‑wear setting spray that locks in glam through Kenyan nights.",
    rating: 4.6,
    reviewsCount: 77,
  },
  {
    id: "garnier-micellar-water-oil-infused",
    slug: "garnier-micellar-cleansing-water-oil-infused",
    name: "Micellar Cleansing Water Oil‑Infused",
    brand: "Garnier",
    category: "skincare",
    priceKes: 1150,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71eX4ZtPipL._SL1500_.jpg",
    description:
      "Gentle makeup remover suitable for heavy Nairobi pollution days.",
    rating: 4.7,
    reviewsCount: 163,
  },
  {
    id: "garnier-even-and-matte-cream",
    slug: "garnier-even-and-matte-face-cream",
    name: "Even & Matte Face Cream",
    brand: "Garnier",
    category: "skincare",
    priceKes: 1050,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71CigXNqvXL._SL1500_.jpg",
    description: "Day cream helping to even hyperpigmentation over time.",
    rating: 4.4,
    reviewsCount: 91,
  },
  {
    id: "nivea-soft-cream",
    slug: "nivea-soft-refreshingly-soft-cream",
    name: "Soft Refreshingly Light Moisturizing Cream",
    brand: "Nivea",
    category: "skincare",
    priceKes: 650,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71uX%2Bvj0XPL._SL1500_.jpg",
    description: "Everyday face and body moisturizer loved across Kenya.",
    rating: 4.6,
    reviewsCount: 210,
  },
  {
    id: "nivea-perfect-radiant-spf50",
    slug: "nivea-perfect-radiant-sunscreen-spf50",
    name: "Perfect & Radiant SPF 50 Face Sunscreen",
    brand: "Nivea",
    category: "skincare",
    priceKes: 1550,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/61usZT6FJiL._SL1200_.jpg",
    description: "High‑protection sunscreen suitable for daily Kenyan sun.",
    rating: 4.5,
    reviewsCount: 84,
  },
  {
    id: "simple-micellar-water",
    slug: "simple-kind-to-skin-micellar-water",
    name: "Kind To Skin Micellar Cleansing Water",
    brand: "Simple",
    category: "skincare",
    priceKes: 950,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71C3bhG3EWL._SL1500_.jpg",
    description: "Fragrance‑free makeup remover for sensitive Kenyan skin.",
    rating: 4.6,
    reviewsCount: 73,
  },
  {
    id: "cerave-foaming-cleanser",
    slug: "cerave-foaming-facial-cleanser",
    name: "Foaming Facial Cleanser",
    brand: "CeraVe",
    category: "skincare",
    priceKes: 2450,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71aBLaC5CzL._SL1500_.jpg",
    description: "Ceramide‑rich cleanser that respects the skin barrier.",
    rating: 4.8,
    reviewsCount: 188,
  },
  {
    id: "cerave-moisturizing-cream",
    slug: "cerave-moisturizing-cream",
    name: "Moisturizing Cream",
    brand: "CeraVe",
    category: "skincare",
    priceKes: 2950,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71tWxuLOuKL._SL1500_.jpg",
    description: "Rich moisturizer ideal for dry highland climates.",
    rating: 4.9,
    reviewsCount: 132,
  },
  {
    id: "cetaphil-gentle-skin-cleanser",
    slug: "cetaphil-gentle-skin-cleanser",
    name: "Gentle Skin Cleanser",
    brand: "Cetaphil",
    category: "skincare",
    priceKes: 2250,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71zO4iAfD0L._SL1500_.jpg",
    description: "Trusted dermatologist‑recommended cleanser for all skin.",
    rating: 4.7,
    reviewsCount: 94,
  },
  {
    id: "neutrogena-hydro-boost-gel",
    slug: "neutrogena-hydro-boost-water-gel",
    name: "Hydro Boost Water Gel",
    brand: "Neutrogena",
    category: "skincare",
    priceKes: 2450,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71iHyBs64OL._SL1500_.jpg",
    description: "Lightweight hydrating gel ideal for humid coastal weather.",
    rating: 4.8,
    reviewsCount: 167,
  },
  {
    id: "neutrogena-sunscreen-dry-touch",
    slug: "neutrogena-ultra-sheer-dry-touch-spf55",
    name: "Ultra Sheer Dry‑Touch Sunscreen SPF 55",
    brand: "Neutrogena",
    category: "skincare",
    priceKes: 2650,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71Ov8hFhQZL._SL1500_.jpg",
    description: "High‑protection sunscreen that feels weightless on skin.",
    rating: 4.6,
    reviewsCount: 121,
  },
  {
    id: "simple-light-moisturizer",
    slug: "simple-light-hydrating-moisturizer",
    name: "Light Hydrating Moisturizer",
    brand: "Simple",
    category: "skincare",
    priceKes: 1150,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71Tn%2B%2BzM6iL._SL1500_.jpg",
    description: "Gentle daily moisturizer ideal for sensitive skin.",
    rating: 4.5,
    reviewsCount: 72,
  },
  {
    id: "cetaphil-moisturizing-lotion",
    slug: "cetaphil-moisturizing-lotion",
    name: "Moisturizing Lotion",
    brand: "Cetaphil",
    category: "skincare",
    priceKes: 2350,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71f8QkF8VXL._SL1500_.jpg",
    description: "Lightweight hydration suitable for face and body.",
    rating: 4.6,
    reviewsCount: 83,
  },
  {
    id: "cantu-curl-activator-cream",
    slug: "cantu-coconut-curling-cream",
    name: "Coconut Curling Cream",
    brand: "Cantu",
    category: "hair",
    priceKes: 1450,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/711mrsiJwhL._SL1500_.jpg",
    description: "Defines natural curls and coils for Kenyan naturals.",
    rating: 4.8,
    reviewsCount: 203,
  },
  {
    id: "cantu-leave-in-conditioner",
    slug: "cantu-shea-butter-leave-in-conditioning-repair-cream",
    name: "Shea Butter Leave‑In Repair Cream",
    brand: "Cantu",
    category: "hair",
    priceKes: 1350,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71eI8cIvx9L._SL1500_.jpg",
    description: "Rich treatment for relaxed and natural hair.",
    rating: 4.7,
    reviewsCount: 156,
  },
  {
    id: "dark-and-lovely-relaxer-kit",
    slug: "dark-and-lovely-regular-relaxer-kit",
    name: "Regular Relaxer Kit",
    brand: "Dark & Lovely",
    category: "hair",
    priceKes: 850,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71H%2B9kQ3yXL._SL1500_.jpg",
    description: "Salon‑trusted relaxer widely used in Kenyan salons.",
    rating: 4.5,
    reviewsCount: 98,
  },
  {
    id: "ors-olive-oil-hair-food",
    slug: "ors-olive-oil-hair-food",
    name: "Olive Oil Hair Food",
    brand: "ORS",
    category: "hair",
    priceKes: 750,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71ZLZ4QhZWL._SL1500_.jpg",
    description: "Daily scalp nourishment with olive oil.",
    rating: 4.4,
    reviewsCount: 61,
  },
  {
    id: "shea-moisture-curl-enhancing-smoothie",
    slug: "shea-moisture-curl-enhancing-smoothie",
    name: "Coconut & Hibiscus Curl Enhancing Smoothie",
    brand: "Shea Moisture",
    category: "hair",
    priceKes: 2450,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/81QpH1bVt4L._SL1500_.jpg",
    description: "Defines curls while adding moisture and shine.",
    rating: 4.8,
    reviewsCount: 132,
  },
  {
    id: "aunt-jackies-curl-la-la",
    slug: "aunt-jackies-curl-la-la",
    name: "Curl La La Defining Curl Custard",
    brand: "Aunt Jackie’s",
    category: "hair",
    priceKes: 1350,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/81WJKz5oZQL._SL1500_.jpg",
    description: "Rich custard for twist‑outs and wash‑and‑go styles.",
    rating: 4.7,
    reviewsCount: 94,
  },
  {
    id: "ors-olive-oil-edge-control",
    slug: "ors-olive-oil-edge-control",
    name: "Olive Oil Edge Control Hair Gel",
    brand: "ORS",
    category: "hair",
    priceKes: 650,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71s%2B8fW2qDL._SL1500_.jpg",
    description: "Strong hold edge gel for sleek styles.",
    rating: 4.4,
    reviewsCount: 57,
  },
  {
    id: "dark-and-lovely-treatment",
    slug: "dark-and-lovely-3-in-1-treatment",
    name: "3‑in‑1 Deep Conditioner Treatment",
    brand: "Dark & Lovely",
    category: "hair",
    priceKes: 850,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71f6wqB0t7L._SL1500_.jpg",
    description: "Strengthening treatment for relaxed and natural hair.",
    rating: 4.5,
    reviewsCount: 63,
  },
  {
    id: "cantu-shea-butter-shampoo",
    slug: "cantu-shea-butter-cleansing-shampoo",
    name: "Shea Butter Cleansing Shampoo",
    brand: "Cantu",
    category: "hair",
    priceKes: 1250,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71cR8U3YbWL._SL1500_.jpg",
    description: "Gentle cleansing for daily use.",
    rating: 4.5,
    reviewsCount: 59,
  },
  {
    id: "shea-moisture-strengthen-restore-shampoo",
    slug: "shea-moisture-jamaican-black-castor-oil-shampoo",
    name: "Jamaican Black Castor Oil Shampoo",
    brand: "Shea Moisture",
    category: "hair",
    priceKes: 2450,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71N1sQxqk1L._SL1500_.jpg",
    description: "Strengthens hair and reduces breakage.",
    rating: 4.7,
    reviewsCount: 88,
  },
  {
    id: "lattafa-oud-for-glory",
    slug: "lattafa-oud-for-glory",
    name: "Oud For Glory Eau de Parfum 100ml",
    brand: "Lattafa",
    category: "perfumes",
    priceKes: 4500,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71S3ykVfoTL._SL1500_.jpg",
    description: "Deep, luxurious oud loved in Kenyan fragrance circles.",
    rating: 4.9,
    reviewsCount: 187,
  },
  {
    id: "lattafa-raed-luxe",
    slug: "lattafa-raed-luxe",
    name: "Raed Luxe Eau de Parfum 100ml",
    brand: "Lattafa",
    category: "perfumes",
    priceKes: 4200,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71l9U8wE5QL._SL1500_.jpg",
    description: "Modern warm scent ideal for evening Nairobi occasions.",
    rating: 4.7,
    reviewsCount: 102,
  },
  {
    id: "ard-al-zaafaran-dirham",
    slug: "ard-al-zaafaran-dirham-edp",
    name: "Dirham Eau de Parfum 100ml",
    brand: "Ard Al Zaafaran",
    category: "perfumes",
    priceKes: 3200,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71N8zxVdLTL._SL1500_.jpg",
    description: "Fresh citrusy Arabic fragrance popular in East Africa.",
    rating: 4.6,
    reviewsCount: 141,
  },
  {
    id: "afnan-supremacy-in-oud",
    slug: "afnan-supremacy-in-oud",
    name: "Supremacy In Oud Eau de Parfum 100ml",
    brand: "Afnan",
    category: "perfumes",
    priceKes: 5200,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71e1UcuurKL._SL1500_.jpg",
    description: "Bold oud fragrance for statement makers.",
    rating: 4.8,
    reviewsCount: 119,
  },
  {
    id: "afnan-9pm",
    slug: "afnan-9pm-edp",
    name: "9PM Eau de Parfum 100ml",
    brand: "Afnan",
    category: "perfumes",
    priceKes: 4800,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71q3Y0JVpRL._SL1500_.jpg",
    description: "Sweet evening scent ideal for date nights in Nairobi.",
    rating: 4.7,
    reviewsCount: 101,
  },
  {
    id: "ard-al-zaafaran-midnight-oud",
    slug: "ard-al-zaafaran-midnight-oud",
    name: "Midnight Oud Eau de Parfum 100ml",
    brand: "Ard Al Zaafaran",
    category: "perfumes",
    priceKes: 4200,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71YJqBqW7nL._SL1500_.jpg",
    description: "Smoky oud with vanilla and spices.",
    rating: 4.6,
    reviewsCount: 77,
  },
  {
    id: "afnan-turathi-blue",
    slug: "afnan-turathi-blue",
    name: "Turathi Blue Eau de Parfum 100ml",
    brand: "Afnan",
    category: "perfumes",
    priceKes: 5200,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71zZsS3fNWL._SL1500_.jpg",
    description: "Fresh aquatic scent with strong longevity.",
    rating: 4.7,
    reviewsCount: 69,
  },
  {
    id: "lattafa-opulent-red",
    slug: "lattafa-opulent-red",
    name: "Opulent Red Eau de Parfum 100ml",
    brand: "Lattafa",
    category: "perfumes",
    priceKes: 3950,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71n4xP0X2wL._SL1500_.jpg",
    description: "Rich fruity‑floral fragrance with strong projection.",
    rating: 4.6,
    reviewsCount: 88,
  },
  {
    id: "ardell-demi-wispies",
    slug: "ardell-demi-wispies-lashes",
    name: "Demi Wispies Lashes",
    brand: "Ardell",
    category: "tools",
    priceKes: 950,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71M3ctNk6kL._SL1500_.jpg",
    description: "Natural‑glam lash style loved by Kenyan makeup artists.",
    rating: 4.8,
    reviewsCount: 211,
  },
  {
    id: "makeup-brush-set-12pc",
    slug: "premium-12pc-makeup-brush-set",
    name: "Premium 12‑Piece Makeup Brush Set",
    brand: "Generic Tools",
    category: "tools",
    priceKes: 1850,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71qUQWGWpDL._SL1500_.jpg",
    description: "Full face brush set with soft synthetic bristles.",
    rating: 4.5,
    reviewsCount: 76,
  },
  {
    id: "beauty-blender-sponge",
    slug: "teardrop-beauty-blender-sponge",
    name: "Teardrop Beauty Blender Sponge",
    brand: "Generic Tools",
    category: "tools",
    priceKes: 450,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/61Y1YPWqsxL._SL1500_.jpg",
    description: "Latex‑free sponge for seamless foundation blending.",
    rating: 4.6,
    reviewsCount: 54,
  },
  {
    id: "wig-cap-pack",
    slug: "nude-wig-cap-pack",
    name: "Nude Wig Cap Pack",
    brand: "Generic Tools",
    category: "tools",
    priceKes: 350,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71xULICwhGL._SL1500_.jpg",
    description: "Breathable wig caps suitable for daily wear.",
    rating: 4.4,
    reviewsCount: 38,
  },
  {
    id: "satin-bonnet-adjustable",
    slug: "adjustable-satin-bonnet",
    name: "Adjustable Satin Bonnet",
    brand: "Generic Tools",
    category: "tools",
    priceKes: 750,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71iMQLXk9cL._SL1500_.jpg",
    description: "Protective night bonnet for natural and relaxed hair.",
    rating: 4.6,
    reviewsCount: 63,
  },
  {
    id: "double-sided-edge-brush",
    slug: "double-sided-edge-brush-comb",
    name: "Double‑Sided Edge Brush & Comb",
    brand: "Generic Tools",
    category: "tools",
    priceKes: 250,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71S1sHmc5eL._SL1500_.jpg",
    description: "Handy tool for sleek edges and baby hairs.",
    rating: 4.5,
    reviewsCount: 41,
  },
  {
    id: "makeup-organizer-acrylic",
    slug: "acrylic-makeup-organizer",
    name: "Acrylic Makeup Organizer",
    brand: "Generic Tools",
    category: "tools",
    priceKes: 1650,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71q7mQFqMZL._SL1500_.jpg",
    description: "Clear organizer for vanity and bathroom.",
    rating: 4.4,
    reviewsCount: 37,
  },
  {
    id: "brush-cleaner-mat",
    slug: "silicone-brush-cleaner-mat",
    name: "Silicone Brush Cleaner Mat",
    brand: "Generic Tools",
    category: "tools",
    priceKes: 550,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71z1vC0F7qL._SL1500_.jpg",
    description: "Helps deep clean makeup brushes quickly.",
    rating: 4.6,
    reviewsCount: 52,
  },
  {
    id: "compact-mirror-led",
    slug: "compact-led-makeup-mirror",
    name: "Compact LED Makeup Mirror",
    brand: "Generic Tools",
    category: "tools",
    priceKes: 950,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71JH9mEo8bL._SL1500_.jpg",
    description: "Travel‑friendly mirror with LED lighting.",
    rating: 4.5,
    reviewsCount: 45,
  },
  {
    id: "tweezers-set",
    slug: "precision-tweezers-set",
    name: "Precision Tweezers Set",
    brand: "Generic Tools",
    category: "tools",
    priceKes: 650,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71o6Qkqg8bL._SL1500_.jpg",
    description: "Brow and lash application tweezers.",
    rating: 4.5,
    reviewsCount: 41,
  },
];

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string) {
  return products.filter((p) => p.category === category);
}

export function searchProducts(term: string) {
  const query = term.trim().toLowerCase();
  if (!query) return products;
  return products.filter((p) => {
    return (
      p.name.toLowerCase().includes(query) ||
      p.brand.toLowerCase().includes(query) ||
      p.category.toLowerCase().includes(query)
    );
  });
}
